name: Petto
version: 0.0.1
author: Nate B. Wangsutthitham (@ThePooE)
main: me.thepooe.petto.Main
website: github.com/thepooe/petto
commands:
  petto:
    description: Say hello to Petto
    usage: /petto