name: Petto
version: 0.0.1
author: Nate B. W. (@ThePooE)
main: com.thepooe.petto.Petto
website: github.com/thepooe/petto

commands:
  petto:
    description: Say hello to Petto
    usage: /petto
  pettoCreate:
   description: Create a pet, leaving player blank default in the user of the command
   usage:
     /petto create [type] [player]
     e.g. /petto create wolf
